wechat:
  baseUrl: https://api.weixin.qq.com/cgi-bin
  wechatAPIs: 
    #获取access_token
    getAccessToken: 
      url: ${wechat.baseUrl}/token
      paramMap: 
        grant_type: client_credential
        appid: ${wechat.appId}
        secret: ${wechat.appSecret}
    #获取微信服务器IP地址
    getWechatIp.url: ${wechat.baseUrl}/getcallbackip
    #微信网络检查
    checkNet: 
      url: ${wechat.baseUrl}/callback/check
      method: POST
      paramType: JSON
      paramMap: 
        action: all
        check_operator: DEFAULT
    #自定义菜单
    #菜单查询
    getMenu.url: ${wechat.baseUrl}/menu/get
    #菜单创建
    createMenu: 
      url: ${wechat.baseUrl}/menu/create
      method: POST
      paramType: JSON
    removeMenu.url: ${wechat.baseUrl}/menu/delete
    getSelfmenu.url: ${wechat.baseUrl}/get_current_selfmenu_info