wechat: 
  wechatAPIs: 
    #获取access_token
    getAccessToken: 
      url: https://api.weixin.qq.com/cgi-bin/token
      paramMap: 
        grant_type: client_credential
        appid: ${wechat.appId}
        secret: ${wechat.appSecret}
    #获取微信服务器IP地址
    getWechatIp.url: https://api.weixin.qq.com/cgi-bin/getcallbackip
    #微信网络检查
    checkNet: 
      url: https://api.weixin.qq.com/cgi-bin/callback/check
      method: POST
      paramType: JSON
      paramMap: 
        action: all
        check_operator: DEFAULT
    #自定义菜单
    #菜单查询
    getMenu.url: https://api.weixin.qq.com/cgi-bin/menu/get
    #菜单创建
    createMenu: 
      url: https://api.weixin.qq.com/cgi-bin/menu/create
      method: POST
      paramType: JSON 